### ISSUE TITLE
Test failures due to hash randomisation in perl 5.17.6

### ISSUE THREAD

**Issue by andk** [thaljef/Parse-CPAN-Perms#1]
Since bleadperl v5.17.5-518-g7dc8663 some of your tests in are failing. That commit introduced hash key randomization and it seems that one test (in t/MBNA.t) is hit by that. Find a sample fail report at: 

http://www.cpantesters.org/cpan/report/104cbbb2-fd76-11e2-8866-81bcf1ff63fb

You can read more about the change at http://perl5.git.perl.org/perl.git/commit/7dc8663964c66a698d31bbdc8e8abed69bddeec3 or at http://www.perlmonks.org/?node_id=1005122 

HTH && Regards,

**Comment by thaljef** [comment]
Fixed in 0c82d800 and shipped as Parse-CPAN-Perms-0.003.  Thanks for letting me know.

Have a happy New Year!
